# Generated by Django 2.2.4 on 2019-10-14 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='img_a',
            field=models.TextField(default='asdf'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='img_b',
            field=models.TextField(default='asdf'),
            preserve_default=False,
        ),
    ]
